apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nix-helm-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/nix-helm-charts
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true