name: Deploy with Nix Helm Generator
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
      - name: Test Nix Helm Generator
        run: nix develop -c -- nix flake check

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
      - name: Generate Charts
        run: nix develop -c -- nix eval --json .#my-app > charts.json
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: charts.json
          images: |
            my-app:${{ github.sha }}